### PR TITLE
Add support for multiple subreddits.

### PR DESCRIPTION
**Pull request by bbkane**
Really cleanly written script! This pull request adds the ability to download from multiple subreddits with one run. The only thing I'm not happy about is modifying the flag `--subreddit` to `--subreddits`, which breaks anyone's script depending on this (the short form `-s` still works). I'd be happy to change that (maybe a parser subgroup?) if necessary.

### CODE REVIEW

**Comment by Nairwolf** [comment]
Hi, this is just my opinion, I'm not the maintainer of this script. 

It's very useful to being able to download multiple subreddits in the same time.  But, I have two things to say : 
- Maybe it's not necessary to use the argument `--subreddits`, maybe `--subreddit` is enough. 
- That would be better if pictures were saved in different directories, called by the subreddit name. 

For the second option, if you like it, I would be happy to change that.

**Comment by bbkane** [comment]
I'm fine with the first option because the `--subreddits` option works just like `--subreddit` when used with one option. I use this script to download wallpapers for my computer, so I would prefer all of my photos go into one directory. Maybe add another option that downloads them to sub-directories, but I really want an option (or the default) to put all the subreddits into one directory.

**Comment by nagracks** [comment]
Thank you for PR

**Comment by nagracks** [comment]
@Nairwolf I am interested to see how you will do it. (the second option)

**Comment by Nairwolf** [comment]
Okay, I will work on that next week ;)

**Pull request closed without merging**
