### PR TITLE
Add config and separate_dirs options

### PR DESCRIPTION
**Pull request by bbkane**
I can now use a config!

The config format is JSON, which I'm not ecstatic about, but it was far less awkward to implement than a configparser implementation and I didn't want to add a configobj (or other) dependency.

### CODE REVIEW

**Comment by bbkane** [comment]
I need to change the write_config option to write to a file instead of just the screen. That way we can ensure it's UTF-8 encoding.

**Comment by nagracks** [comment]
Thank you for contribution

**Comment by bbkane** [comment]
Thank you for this script. It daily brightens up my wallpaper and it's become some of the most fulfilling code I've worked on.

**Comment by nagracks** [comment]
I'm glad you like it

**Pull request closed without merging**
